services:
  postgres:
    image: postgres
    networks:
      - member-management-net
    volumes:
      - member-management-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  member-management-backend:
    depends_on:
      - postgres
    image: member-management-backend
    ports:
      - "8080:8080"
    networks:
      - member-management-net
    environment:
      TZ: Asia/Tokyo
  member-management-frontend:
    image: member-management-frontend
    ports:
      - "3000:80"
    networks:
      - member-management-net
networks:
  member-management-net:
    external: true
volumes:
  member-management-vol:
    external: true
