spring.application.name=Member Management System
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# 開発環境をデフォルトに設定
spring.profiles.active=dev
